FROM ubuntu:18.04
  
COPY requirements_qpu.txt ./requirements.txt
  
RUN apt-get update
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install -y python3.7
RUN apt-get install -y python3-pip
RUN apt install -y libsm6
RUN apt install -y libxrender1
RUN apt install -y python-qt4
RUN apt-get install -y cmake

RUN pip3 install -r requirements.txt


RUN mkdir -p /workdir
WORKDIR /workdir


RUN export LC_ALL=C.UTF-8
RUN export LANG=C.UTF-8



CMD ["/bin/bash"]

