version: '3.1'

services:
  dev:
    image: dev
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - 8888:8888
    volumes:
      - ~/:/workdir
      - ~/DOCKER_HOME/:/root
    restart: unless-stopped

