#FROM ubuntu:20.04
FROM tensorflow/tensorflow:latest-gpu-py3

RUN apt-get update
RUN apt-get install -y tmux libsm6 libxext6 libxrender-dev 
RUN apt-get install -y python3-pip
RUN apt-get install -y libhdf5-serial-dev netcdf-bin libnetcdf-dev

COPY requirements_dev.txt ./requirements.txt
RUN pip3 install -r requirements.txt


RUN mkdir -p /workdir
WORKDIR /workdir

#RUN apt-get clean && apt-get update && apt-get install -y locales
#RUN locale-gen ru_RU.UTF-8
#RUN update-locale LANG=ru_RU.UTF-8 LC_MESSAGES=POSIX

RUN export LC_ALL=C.UTF-8
RUN export LANG=C.UTF-8

COPY entry.sh /entry.sh
ENTRYPOINT ["/bin/bash" ,"/entry.sh"] 
CMD ["/bin/bash"]
